### ISSUE TITLE
Add makefile

### ISSUE THREAD

**Issue by Jan-PieterBaert** [ZeusWPI/g2-backend#22]
I would like a makefile, this makes building, running and cleaning easier

**Comment by mcbloch** [comment]
There is a dockerfile+docker-compose now that does most of the stuff.
Do you still want a makefile for a non docker setup?

**Comment by Jan-PieterBaert** [comment]
That would be nice, but that would only be for production so we can wait a bit for it

**Comment by mcbloch** [comment]
I think this can be closed because of #41. 
There is an entry to build using docker compose, which is the no fuzz setup. It sets up the database and configs for you.
And there is an entry to just use the jar with your local development config. (This requires a jar to be build by `lein uberjar` and a database to be available.)

Is this enough?

**Comment by Jan-PieterBaert** [comment]
it looks good to me, if anything else should be added we can reopen this issue.
